#server:
#  port: 8081
#  servlet:
#    context-path: /resource-server
####### resource server configuration properties
spring:
  servlet:
    multipart:
      max-file-size: 90MB
      max-request-size: 90MB
logging:
  level:
    root: debug
    org:
      springframework:
        web: debug
      hibernate:
        internal:
          util: INFO
######################### my variables #######################################
NUM_THREADS: 4
REQ_PARALLEL: 4
base_fe_url: http://localhost:8089/
realm: baeldung
