server:
  port: 8081
  servlet:
    context-path: /resource-server
  tomcat:
    max-swallow-size: 90MB
    connection-timeout: 120s
####### resource server configuration properties
spring:
  servlet:
    multipart:
      max-file-size: 90MB
      max-request-size: 90MB
logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
      hibernate:
        internal:
          util: INFO
      apache:
        coyote:
          http11:
            Http11InputBuffer: OFF
######################### my variables #######################################
NUM_THREADS: 4
REQ_PARALLEL: 4
base_fe_url: http://localhost:8089/
realm: baeldung
